providers = ["node", "python"]

[variables]

NODE_ENV = 'production'

[deploy]
startCommand = "cd frontend_react && npm install && npm run build && cd .. && python manage.py migrate && python manage.py collectstatic && gunicorn backend_django.wsgi"