# Generated by Django 5.0.6 on 2024-05-21 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_cliente_codigo_producto_codigo_proveedor_codigo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='proveedor',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='ventas.proveedor'),
            preserve_default=False,
        ),
    ]
