# Generated by Django 5.0.6 on 2024-06-23 19:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_solicitud_proveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='fecha_solicitud',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='razon_cancelacion',
            field=models.CharField(blank=True, choices=[('NI', 'No estoy interesado en el producto'), ('NB', 'No encontré lo que buscaba'), ('NC', 'No hay la cantidad suficiente que necesito'), ('PE', 'El precio es muy elevado'), ('NP', 'La marca/proveedor no es la que busco'), ('SR', 'Solicitud cancelada repentinamente')], max_length=2, null=True),
        ),
    ]
