# Generated by Django 5.0.6 on 2024-06-24 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_alter_solicitud_fecha_solicitud_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='codigo',
            field=models.CharField(blank=True, max_length=7, unique=True),
        ),
    ]
